import './globals.css';
import { ReduxProvider } from '@/redux/provider';

export const metadata = {
  title: 'E-Commerce App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
